- hosts: docker
  tasks:
     - name: stop container
       shell: docker container stop dockeradja4
     - name: remove container
       shell: docker container rm dockeradja4
     - name: docker image removal
       shell: docker image rm -f oalalif/gadja-v5
     - name: create new container
       shell: docker run -itd --name dockeradja4 oalalif/gadja-v5